name: Darren J. Ryan
favicon: null
layout_spectrum: 0.7397388
typography_spectrum: 0.5160155
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#E8B588'
    - '#BC8276'
    - '#7FA4A3'
  brandStrength: 0.4375
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5846061
purpose: []
