layout_spectrum: 0.7397388
color:
  saturation: 0.01967752
  lightness: 0.9623771
  brandStrength: 0.4740883
  brandColors:
    - '#FFFFFF'
    - '#E8B588'
    - '#BC8276'
    - '#7FA4A3'
  rhythmicContrast: 0.5846061
typography_spectrum: 0.5160155
name: Darren J. Ryan
